version: '3.8'

services:
  web:
    build: ./fe
    container_name: frontend
    ports:
      - "5002:5002"
    networks:
      - shieldnet
    depends_on:
      - backend-service
      - mysqldb

  backend-service:
    build: ./be
    container_name: backend
    ports:
      - "5001:5001"
    networks:
      - shieldnet
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crypto_db
    ports:
      - "3306:3306"
    networks:
      - shieldnet

networks:
  shieldnet:
    driver: bridge
